config/routes.rb
MailFunnelServer::Application.routes.draw do

  resources :campaign_product_leads
  resources :job_queues
  resources :campaigns do
	  resources :hooks
  end
	# http://localhost:3001/API/
	mount API => '/'

	# http://localhost:3001/RESOURCE

	resources :email_lists do
		resources :emails
	end

	resources :emails
  resources :jobs
	resources :hooks

	resources :apps do
		resources :campaigns do
			resources :email_lists do
				resources :email
			end
			resources :jobs
		end
		resources :email_lists do
			resources :email
		end
	end


end

app/models/campaign_product_lead.rb
class CampaignProductLead < ApplicationRecord
  belongs_to :app
  belongs_to :campaign
  belongs_to :job
  belongs_to :EmailList
  belongs_to :email
end

app/controllers/campaign_product_leads_controller.rb
class CampaignProductLeadsController < ApplicationController
  before_action :set_campaign_product_lead, only: [:show, :update, :destroy]

  # GET /campaign_product_leads
  def index
    @campaign_product_leads = CampaignProductLead.all

    render json: @campaign_product_leads
  end

  # GET /campaign_product_leads/1
  def show
    render json: @campaign_product_lead
  end

  # POST /campaign_product_leads
  def create
    @campaign_product_lead = CampaignProductLead.new(campaign_product_lead_params)

    if @campaign_product_lead.save
      render json: @campaign_product_lead, status: :created, location: @campaign_product_lead
    else
      render json: @campaign_product_lead.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /campaign_product_leads/1
  def update
    if @campaign_product_lead.update(campaign_product_lead_params)
      render json: @campaign_product_lead
    else
      render json: @campaign_product_lead.errors, status: :unprocessable_entity
    end
  end

  # DELETE /campaign_product_leads/1
  def destroy
    @campaign_product_lead.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_product_lead
      @campaign_product_lead = CampaignProductLead.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def campaign_product_lead_params
      params.require(:campaign_product_lead).permit(:app_id, :product_identifier, :campaign_id, :job_id, :sold, :sale_ammount, :EmailList_id, :email_id, :BuyDate, :ClickDate)
    end
end

app/views/campaign_product_leads/_form.html.erb
<%= form_for(campaign_product_lead) do |f| %>
  <% if campaign_product_lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign_product_lead.errors.count, "error") %> prohibited this campaign_product_lead from being saved:</h2>

      <ul>
      <% campaign_product_lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_id %>
    <%= f.text_field :app_id %>
  </div>

  <div class="field">
    <%= f.label :product_identifier %>
    <%= f.number_field :product_identifier %>
  </div>

  <div class="field">
    <%= f.label :campaign_id %>
    <%= f.text_field :campaign_id %>
  </div>

  <div class="field">
    <%= f.label :job_id %>
    <%= f.text_field :job_id %>
  </div>

  <div class="field">
    <%= f.label :sold %>
    <%= f.text_field :sold %>
  </div>

  <div class="field">
    <%= f.label :sale_ammount %>
    <%= f.text_field :sale_ammount %>
  </div>

  <div class="field">
    <%= f.label :EmailList_id %>
    <%= f.text_field :EmailList_id %>
  </div>

  <div class="field">
    <%= f.label :email_id %>
    <%= f.text_field :email_id %>
  </div>

  <div class="field">
    <%= f.label :BuyDate %>
    <%= f.datetime_select :BuyDate %>
  </div>

  <div class="field">
    <%= f.label :ClickDate %>
    <%= f.datetime_select :ClickDate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaign_product_leads/edit.html.erb
<h1>Editing Campaign Product Lead</h1>

<%= render 'form', campaign_product_lead: @campaign_product_lead %>

<%= link_to 'Show', @campaign_product_lead %> |
<%= link_to 'Back', campaign_product_leads_path %>

app/views/campaign_product_leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaign Product Leads</h1>

<table>
  <thead>
    <tr>
      <th>App</th>
      <th>Product identifier</th>
      <th>Campaign</th>
      <th>Job</th>
      <th>Sold</th>
      <th>Sale ammount</th>
      <th>Emaillist</th>
      <th>Email</th>
      <th>Buydate</th>
      <th>Clickdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_product_leads.each do |campaign_product_lead| %>
      <tr>
        <td><%= campaign_product_lead.app %></td>
        <td><%= campaign_product_lead.product_identifier %></td>
        <td><%= campaign_product_lead.campaign %></td>
        <td><%= campaign_product_lead.job %></td>
        <td><%= campaign_product_lead.sold %></td>
        <td><%= campaign_product_lead.sale_ammount %></td>
        <td><%= campaign_product_lead.EmailList %></td>
        <td><%= campaign_product_lead.email %></td>
        <td><%= campaign_product_lead.BuyDate %></td>
        <td><%= campaign_product_lead.ClickDate %></td>
        <td><%= link_to 'Show', campaign_product_lead %></td>
        <td><%= link_to 'Edit', edit_campaign_product_lead_path(campaign_product_lead) %></td>
        <td><%= link_to 'Destroy', campaign_product_lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign Product Lead', new_campaign_product_lead_path %>

app/views/campaign_product_leads/new.html.erb
<h1>New Campaign Product Lead</h1>

<%= render 'form', campaign_product_lead: @campaign_product_lead %>

<%= link_to 'Back', campaign_product_leads_path %>

app/views/campaign_product_leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @campaign_product_lead.app %>
</p>

<p>
  <strong>Product identifier:</strong>
  <%= @campaign_product_lead.product_identifier %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @campaign_product_lead.campaign %>
</p>

<p>
  <strong>Job:</strong>
  <%= @campaign_product_lead.job %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @campaign_product_lead.sold %>
</p>

<p>
  <strong>Sale ammount:</strong>
  <%= @campaign_product_lead.sale_ammount %>
</p>

<p>
  <strong>Emaillist:</strong>
  <%= @campaign_product_lead.EmailList %>
</p>

<p>
  <strong>Email:</strong>
  <%= @campaign_product_lead.email %>
</p>

<p>
  <strong>Buydate:</strong>
  <%= @campaign_product_lead.BuyDate %>
</p>

<p>
  <strong>Clickdate:</strong>
  <%= @campaign_product_lead.ClickDate %>
</p>

<%= link_to 'Edit', edit_campaign_product_lead_path(@campaign_product_lead) %> |
<%= link_to 'Back', campaign_product_leads_path %>